/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Tue Jul 11 13:07:10 2017. */

#include "laserbug.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t LaserMessage_fields[4] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, LaserMessage, distance, distance, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, LaserMessage, duty, distance, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, LaserMessage, temperature, duty, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
